[package]
name = "dims"
version = "0.3.0"
authors = ["william"]
edition = "2021"
keywords = ["measurement", "dimension", "unit"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.dims_core]
path = "../dims_core"
default-features = false
[dependencies.dims_macro]
path = "../dims_macro"
default-features = false
[features]
default = ["us", "si", "str"]
# Pass each of these along to core
no_std = ["dims_core/no_std"]
str = ["dims_core/str","dims_macro/str"]
f64 = ["dims_core/f64"]
us = []
si = []
debug_us = []