name: Rust

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: >-
        cargo build --verbose &&
        cargo build --manifest-path test_nostd/Cargo.toml
    - name: Run tests
      run: >-
        cargo test --verbose &&
        cargo test --manifest-path test_nostd/Cargo.toml
